### ISSUE TITLE
How long it takes to find all craftable color?

### ISSUE THREAD

**Issue by zmyme** [ANRAR4/DyeLeatherArmor#1]
Hi, i am also interested in calculate all possible colors of leather in minecraft, and after some calculations i found that for 8 slots, there is C_{24}^{16}=735471 possible recipes, and it sems that we should test at least 735471**2 possible combinations(assume depth is 2 at maximum, the actual number should be much larger than this estimation) to find all the possible colors, which seems a lot of calculations, so i am wondering how long it takes for you to calculate all the possible colors? Thank you!

**Comment by ANRAR4** [comment]
For some context: On a Ryzen 9 3900x using 18 threads the program should take about 6 hours to run.

All 735470 combinations listed in [colourOptions_depth_8.log](https://github.com/ANRAR4/DyeLeatherArmor/blob/main/colourOptions_depth_8.log) are tested for each newly found colour. So the first iteration tests all 735470 possible combinations on undyed leather armor and finds 606315 craftable colours. The second iteration tests all 735470 possible combinations on the 606315 newly found colours and finds 5015047 new craftable colours and so on, until there are no newly found colours. The deepest recipe (colour #bc951b) requires 13 crafting steps.

The numbers are for versions 1.12 and above. They vary for earlier versions.

**Comment by zmyme** [comment]
Thank you for your reply! I once planned to write a python-based single-threaded script to calculate all possible colors and it seems this is not possible to get the answer in acceptable time. :), i am gonna to try this with c++, thank you!

**Comment by zmyme** [comment]
BTW, i wrote a c++ version at https://github.com/zmyme/LuckyColorRecipeCalculator/blob/main/leatherColorCombinationsCalculator.cpp, it takes about 1h to search all the colors on Intel Silver 4210R*2 (10C20T * 2) with thread=40.
