### ISSUE TITLE
[Question] Would I be able to calculate exactly how much of each dye I would need to craft every color combination of leather armor with this??

### ISSUE THREAD

**Issue by Cloveian** [ANRAR4/DyeLeatherArmor#4]
I am trying to make every possible color of leather armor in hardcore minecraft and in new snapshot with auto crafters it's now somewhat feasible.

**Comment by ANRAR4** [comment]
Yes, you could calculate it from the results this programm produces.
In fact i calculated it already

To craft one armorpiece of each colour you would need the following dyes:

> "black": 5529433,
  "red": 3842620,
  "green": 2998567,
  "brown": 2602584,
  "blue": 3084816,
  "purple": 3362714,
  "cyan": 4138849,
  "light grey": 1408551,
  "grey": 1959371,
  "pink": 2696590,
  "lime": 4833997,
  "yellow": 3870353,
  "light blue": 5219694,
  "magenta": 2353105,
  "orange": 3593163,
  "white": 3509541

It should be noted that the recipes produced by this programm are optimised to use as few crafting steps as possible, not as few dyes as possible, so other recipes could save a few dyes.
