### ISSUE TITLE
What is the most steps you have seen a single color require?

### ISSUE THREAD

**Issue by LunaDisconnected** [ANRAR4/DyeLeatherArmor#5]
I want to make a library of all the dye recipes and i was wondering how many steps do most colors require? Are there any colors that are more than 4 steps?

**Comment by ANRAR4** [comment]
In 1.12+ the colours have the following distribution:
> 1 step: 606315
2 steps: 5015047
3 steps: 74649
4 steps: 12932
5 steps: 3310
6 steps: 851
7 steps: 231
8 steps: 72
9 steps: 29
10 steps: 9
11 steps: 2
12 steps: 2
13 steps: 1

The colour requiring the most steps is `#bc951b` with 13 steps.
