### ISSUE TITLE
How to generate colourOptions_depth_8.log

### ISSUE THREAD

**Issue by OutrightWings** [ANRAR4/DyeLeatherArmor#6]
The code to my understanding takes this fie as an input to do all its calculations. I would like to expand the calculator to handle some [custom dye colors](https://www.curseforge.com/minecraft/mc-mods/dye-depot), but nowhere on the github is it mentioned how to acquire these combinations.

**Comment by ANRAR4** [comment]
`colourOptions_depth_8.log` can be generated by:
- assigning an index to each colour(corresponding to https://github.com/ANRAR4/DyeLeatherArmor/blob/main/calculateCombinations.c#L108 - 1)
- for 1 to 8 ingredients:
	- combining each of the 16 colours with each combination from all previous iterations
	- sorting the ingredients of the combination
	- checking if the sorted combination has already been added(to prevent unnecessary calculations, as green + lime = lime + green)
	- adding the combination to the list of combinations
- writing all combinations to a file(as described in README.md)

> `colourOptions_depth_8.log` contains a list of all possible and unique dye combinations using up to 8 dyes. Each dye is represented using 5 bits in the uint64_t represented by each row. (0 = no colour(end of dye list), 1 = black, 16 = white etc((<1.13 colour subids) + 1)). The file is used as input for `calculateCombinations.c`.

If there are more than 31 dyes you would need to use more than 5 bits for each ingredient and also adapt `getDyesForInt` in `calculateCombinations.c`

You would also need to change the combinations count in https://github.com/ANRAR4/DyeLeatherArmor/blob/main/calculateCombinations.c#L13 as well as the list of colours in https://github.com/ANRAR4/DyeLeatherArmor/blob/main/calculateCombinations.c#L108

**Comment by Beaudeclan** [comment]
hello ANRAR4 i tried making armor pieces with these hexs but it says its possible but it doesn't work in game

**Comment by ANRAR4** [comment]
Is your question related to this issues question? Otherwise creating a new issue would be better.

Anyway, if you are using Minecraft Java Edition and have selected the correct version the recipes should be correct.
Which colour(s) did you try to make and in which Minecraft version?
